vspring.application.name=wem-sc-vendas
spring.datasource.url=jdbc:postgresql://postgres:[jhonata968574123]@db.aicpfcodxslhwnqgihwr.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=jhonata968574123
