server.port=8080
spring.application.name=wem-sc-vendas
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.aicpfcodxslhwnqgihwr
spring.datasource.password=jhonata968574123


# Configurações extras do Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# O 'update' faz o Spring criar as tabelas sozinho na Supabase
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
